### ISSUE TITLE
Feature Request: Country TimeZone

### ISSUE THREAD

**Issue by vercotux** [commerceguys/intl#38]
Pretty much what the title says. Would it be possible to add a `getTimezone()` method to Country?

**Comment by bojanz** [comment]
Found a country to timezone mapping here: https://github.com/unicode-cldr/cldr-core/blob/master/supplemental/windowsZones.json

Problems:
1) A country can span multiple timezones. That means we can't have Country::getTimezone(), it would need to be Country::getTimezones(). Which makes me think that it makes more sense to have a Timezone specific API (TimezoneMapper? TimezoneRepository) which also leaves the door open for returning GMT offsets  and non-local names (CEST instead of Europe/Belgrade) as well.

2) We would need to verify that each _type maps to an actual PHP timezone, as documented on http://php.net/manual/en/timezones.php

I have no need for this functionality, so someone else would need to champion it and submit a PR for us to discuss.

**Comment by bojanz** [comment]
Actually, looks like PHP can give you a list of timezones per country out of the box:
http://php.net/manual/en/datetimezone.listidentifiers.php

Tried this:
```
$timezone_identifiers = DateTimeZone::listIdentifiers(\DateTimeZone::PER_COUNTRY, 'US');
```
And it worked!

**Comment by bojanz** [comment]
We could add a Country getTimezones() method that proxies to the PHP one, for discoverability.

**Comment by vercotux** [comment]
Revisiting this and considering all the great points you made I am no longer convinced that we need this feature.

As you pointed out countries may span multiple timezones, which makes it illogical to have `getTimezone()` in `Country`. Like you also pointed out, there remains the possibility for `getTimezones()`. However, from my experience, in most use cases that I have encountered I always needed one specific timezone, so perhaps this is not really the most useful feature.

The only way to get one single timezone would be to map it from geo coordinates, which is probably outside the scope of this project.
