### ISSUE TITLE
NumberFormatter no longer accepts floats

### ISSUE THREAD

**Issue by Propaganistas** [commerceguys/intl#68]
I've noticed that `NumberFormatter` underwent some changes from `0.*` tot `1.*`. More specifically the percent style got some breaking changes. I'm just curious if the following ones are intended.

```php
// version 0.*
$formatter->format(75, ['style' => 'percent']); // 75%

// version 1.*
$formatter->format(75, ['style' => 'percent']); // 7500%
````

```php
// version 0.*
$formatter->format(0.75, ['style' => 'percent']); // 0.75%

// version 1.*
$formatter->format(0.75, ['style' => 'percent']); // Exception (floats cannot be passed)
$formatter->format('0.75', ['style' => 'percent']); // 75%
````

**Comment by bojanz** [comment]
Everything except the Exception was done intentionally to sync the formatter with php's NumberFormatter (which formats percentages the same way). See #67.

The float exception is a regression caused by adding rounding, since rounding always requires a string (bcmath). But we can cast to string before then.

**Comment by Propaganistas** [comment]
Ok seems legit!
I'd definitely vouch for implementing a quick string cast.
