### ISSUE TITLE
Walloon should not be filtered out

### ISSUE THREAD

**Issue by herrwalter** [commerceguys/intl#71]
- Walloon (official iso 'wa' code)
- Taiwanese (or Taiyu)
- Montenegrin (official iso 'cnr')

We make some translations in and to these languages. Could you please add them so we can add them to our website? 
Or how can we add them ourselves?

Thank you

**Comment by bojanz** [comment]
I checked, Taiyu doesn't exist in CLDR. The ISO code for Montenegrin is still "sr-ME". 
"Walloon" is filtered out, probably by accident.

If you think that the Taiyu / Montenegrin parts are a mistake, open a CLDR issue: http://unicode.org/cldr/trac/
CLDR has releases every 6 months, which is when we pull in changes from upstream.

**Comment by herrwalter** [comment]
@bojanz Thanks! 
Taiyu could also be Taiwanese
Couldn't find it on the CLDR, maybe you can?

**Comment by herrwalter** [comment]
Well, i'd added a feature request to CLDR
https://unicode.org/cldr/trac/ticket/11412

**Comment by herrwalter** [comment]
@bojanz Any change this is going to be updated this week?

**Comment by bojanz** [comment]
Circled back to this, now that we've updated to CLDR v34.
Unfortunately, v34 did not bring the new language code for Montenegrin, and in fact, the language itself is missing from all locales except English, it is completely untranslated.

Due to that, I'm going to have to skip adding Montenegrin until the next CLDR release.
You will have to override LanguageRepository to add it yourself.

Adding Walloon now, since that one is fine.
