### ISSUE TITLE
Inuktitut is omitted even though it is not in the $ignoredLocales array 

### ISSUE THREAD

**Issue by greatislander** [commerceguys/intl#85]
Hello,

I'm looking into using this library for a project in Canada and as such need support for Inuktitut (`iu`) (which is an official language in the territory of [Nunavut](https://www.gov.nu.ca)). I notice that Inuktitut does not appear in the generated resources, even though it is not one of the `$ignoredLocales`: https://github.com/commerceguys/intl/blob/90b4f75c4917927a1960c0dcaa002a91ab97f5d5/scripts/generate_base.php#L31-L57

I appreciate the rationale behind #79 but I'm wondering:

1. Why it's not included in the library even though it's not explicitly ignored.
2. If this language could be included in the library, as there are regulatory requirements for its support in Nunavut which our application must meet.

Thanks in advance!

**Comment by bojanz** [comment]
I don't see the iu locale present upstream in CLDR: 
https://github.com/unicode-org/cldr-json/tree/master/cldr-json/cldr-localenames-full/main
https://github.com/unicode-org/cldr-json/tree/master/cldr-json/cldr-numbers-full/main

You might need to ask in [their JIRA](https://unicode-org.atlassian.net/jira/software/c/projects/CLDR/issues/?filter=allissues) about why that is so.

**Comment by greatislander** [comment]
I guess I didn't explain properly—what I'm wondering is why the list of languages (e.g. in `en`) does not include `iu` and some others found in the CLDR repository?

https://github.com/unicode-org/cldr-json/blob/39205fdc027c935e52a268afcf01cd240f3c442d/cldr-json/cldr-localenames-full/main/en/languages.json#L260

It doesn't appear here: https://github.com/commerceguys/intl/blob/master/resources/language/en.json

**Comment by bojanz** [comment]
Ah, I see.

The problem we had is that the full language list is too long and has entries that are not useful in a regular web app context (no users will select Latin or Church Slavic as their UI language, for example), so we decided to narrow it down by filtering it against CLDR's locale list, since that list includes almost every language ever. The key word being almost here, since it appears to not contain Inuktitut.

I would be happy for us add an exception for Inuktitut, or to investigate better ways of filtering the list. The code in question is at https://github.com/commerceguys/intl/blob/master/scripts/generate_language_data.php#L79, and you can see that we already made an exception for "wa".

**Comment by greatislander** [comment]
Thanks for the clarification! I'd be happy to open a PR to add an exception for Inuktitut as a straightforward solution for the immediate problem.
